[module/wired]
type = internal/network
interface = enp5s0
interval = 1.0


; Only icon, no interface or IP
label-connected = 󰈁
label-disconnected = 󰈂


; Padding (optional)
format-connected-padding = 1
format-disconnected-padding = 1
