shell bash
background_opacity .8
background #222136
blur true
blur_strength 8
shell_integration enabled
font_size 20
font_family      family="0xProto Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto