#Source Files
source = ~/.config/hypr/configs/windowrule.conf
source = ~/.config/hypr/configs/windowrulev2.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/display.conf
source = ~/.config/hypr/configs/animations.conf

  
general {
    gaps_in = 4
    gaps_out = 6
    border_size = 2
    col.active_border = rgb(d79921)  
    col.inactive_border = rgb(B3C5FF)
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
  }

decoration {
    rounding = 8
    active_opacity = 1.0
    inactive_opacity = .7
    blur {
        enabled = true 
        size = 2
        passes = 4
        vibrancy = 0.1696
    }
}

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    sensitivity = 0
    numlock_by_default = true
    touchpad {
        natural_scroll = true
    }
}
