general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = hyprlock    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 300                                # 2.5min.
    on-timeout = brightnessctl -s set 1 HDMI-A-1
    on-timeout = brightnessctl -s set 1 DP-1         # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r HDMI-A-1
    on-resume = brightnessctl -r DP-1                 # monitor backlight restore.
}

#
listener {
    lock_cmd = pidof hyprlock || hyprlock
    timeout = 300                                # 5min
    on-timeout = hyprlock            # lock screen when timeout has passed
}

listener {
    timeout = 600                                 # 5.5min
    on-timeout = hyprctl dispatch DP-1 off
    on-timeout = hyprctl dispatch HDMI-A-1 off         # screen off when timeout has passed
    on-resume = hyprctl dispatch dpms on          # screen on when activity is detected after timeout has fired.
}
