;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar

include-file = $HOME/dotfiles/polybar/themes/minimal/include-modules.ini

[bar/main]
monitor = ${env:MONITOR:}
width = 2560
height = 36
bottom = false
fixed-center = true

fonts = "0XProtoNerd-Regular:size=16"

; wm-restack = bspwm
; wm-restack = i3

override-redirect = false

scroll-up = next
scroll-down = prev

enable-ipc = true

background = ${colors.bg}
foreground = ${colors.fg}

; Module separator settings
separator = |
separator-foreground = ${colors.fg-alt}

include-file = $HOME/dotfiles/polybar/fonts.ini

modules-left = dwm-tags fs-root fs-home fs-media fs-music
modules-center = date
modules-right =  tray wired bluetooth pulseaudio

cursor-click = pointer
cursor-scroll = ns-resize

[bar/secondary]
monitor = ${env:MONITOR:}
width = 100%
height = 30
offset-y = 0
bottom = false
fixed-center = true

; wm-restack = bspwm
; wm-restack = i3

override-redirect = false

scroll-up = next
scroll-down = prev

enable-ipc = true

background = ${colors.bg}
foreground = ${colors.fg}

; Module separator settings
separator = |
separator-foreground = ${colors.fg-alt}

include-file = $HOME/dotfiles/polybar/fonts.ini

; Secondary bar modules (no EWMH or systray)
modules-left =
modules-center = title
modules-right = wired pulseaudio date

cursor-click = pointer
cursor-scroll = ns-resize

[settings]
screenchange-reload = true
