monitorv2 {
   output = HDMI-A-1
   mode = 1920x1080@100
   position = 0x0
   scale = 1
   bitdepth = 8
   transform = 0
}
monitorv2 {
   output = DP-1
   mode = 2560x1440@165
   position = 1920x0
   scale = 1
   bitdepth = 10
   transform = 0
   supports_hdr = on
   cm = srgb
   supports_wide_color = on
   sdrbrightness = 1.25
   sdrsaturation = 1
   sdr_max_luminance = 250
   sdr_min_luminance = 1
   min_luminance = 50
   max_luminance = 1500
   max_avg_luminance = 500
}
