#exec = XDG_MENU_PREFIX=arch- kbuildsycoca6
exec-once = hyprpanel
exec-once = hypridle
exec-once = steam -silent
exec-once = systemctl --user start hyprpolkitagent
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
exec-once = nwg-look -a
exec-once = /home/thecoon/dotfiles/scripts/vm-lg.sh
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Breeze-Dark"
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
exec-once = linux-wallpaperengine --no-fullscreen-pause --scaling stretch --screen-root DP-1 --bg 1692834824
exec-once = linux-wallpaperengine --no-fullscreen-pause --scaling stretch --screen-root HDMI-A-1 --bg 1692834824
