# My Keybinds
bind = SUPER, T, exec, kitty
bind = SUPER, Q, killactive,
bind = SUPER, E, exec, dolphin
bind = SUPER, TAB, exec, zen-browser
bind = SUPER, G, exec, looking-glass-client
bind = SUPER, N, exec, kitty nvim
bind = SUPER, C, exec, cursor
bind = SUPER, F, fullscreen
bind = CONTROL SUPER, T, togglefloating
bind = SUPER, L, exec, hyprlock 
bind = SUPER CONTROL, S, exec, grim -g "$(slurp)" && exec notify-send --expire-time=1200 "Screenshot Saved To Pictures"
bind = CONTROLSUPER, L, exec, hyprlock
bind = SUPER, R, exec, rofi -show drun

#Scripts
bind = SUPER SHIFT, R, exec, ~/dotfiles/scripts/sys-reload.sh
bind = CONTROLSUPER, DELETE, exec, ~/dotfiles/scripts/wlogout.sh

#Workspace Controls
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = CONTROLSUPER, 1, workspace, 6
bind = CONTROLSUPER, 2, workspace, 7
bind = SUPER SHIFT, 1, movetoworkspacesilent, 1
bind = SUPER SHIFT, 2, movetoworkspacesilent, 2
bind = SUPER SHIFT, 3, movetoworkspacesilent, 3
bind = SUPER SHIFT, 4, movetoworkspacesilent, 4
bind = SUPER SHIFT, 5, movetoworkspacesilent, 5
bind = CONTROLSUPER SHIFT, 1, movetoworkspacesilent, 6
bind = CONTROLSUPER SHIFT, 2, movetoworkspacesilent, 7
bindm = SUPER, mouse:272, movewindow
bindm = SUPER , mouse:273, resizewindow
