windowrulev2 = opacity 0.9 0.9, xwayland:^(*)$
windowrulev2 = opacity 1 1, class:^(steam_app_)$
windowrulev2 = opacity 0.9 0.9, class:^(Cursor)$
windowrulev2 = opacity 0.9 0.9, initialClass:[kitty]
windowrulev2 = noblur,class:^()$,title:^()$

windowrulev2 = float, title:^(Sign in to Security Device)$
windowrulev2 = size 500 300, title:^(Sign in to Security Device)$
windowrulev2 = move 1753 787, title:^(Sign in to Security Device)$

windowrulev2 = float,class:^(org.gnome.Calendar)$
windowrulev2 = move 4 38, class:^(org.gnome.Calendar)$

windowrulev2 = float,class:^(org.prismlauncher.PrismLauncher)$
windowrulev2 = size 866 618, class:^(org.prismlauncher.PrismLauncher)$


windowrulev2 = size 1033 476, class:^(io.missioncenter.MissionCenter)$
windowrulev2 = move 3438 64, class:^(io.missioncenter.MissionCenter)$
windowrulev2 = float, class:^(io.missioncenter.MissionCenter)$

windowrulev2 = fullscreen, class:^(looking-glass-client)$

windowrulev2 = float, class:^(galculator)$
windowrulev2 = size 413 518, class:^(galculator)$

windowrulev2 = float, class:^(waypaper)$
windowrulev2 = size 828 1130, class:^(waypaper)$

windowrulev2 = float, class:^(it.mijorus.gearlever)$
windowrulev2 = size 571 815, class:^(it.mijorus.gearlever)$

windowrule = move 1110 4%, title:^(Sign in to Security Device)$

workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
#workspace = 4, monitor:DP-1
#workspace = 5, monitor:DP-1
workspace = 4, monitor:HDMI-A-1
workspace = 5, monitor:HDMI-A-1


